from __future__ import annotations

PLUGIN_NAME = "Gluetun Rotate"
PLUGIN_VERSION = "0.1.0"
PLUGIN_DESCRIPTION = (
    "Moves Gluetun to another VPN server when the IPTV provider refuses the current exit "
    "address."
)
USER_AGENT = f"gluetun-rotate/{PLUGIN_VERSION}"

WATCHER_MODULE = "gluetun_rotate.watcher"
RUN_TOKEN_ENV = "GLUETUN_ROTATE_RUN_TOKEN"
API_KEY_ENV = "GLUETUN_ROTATE_API_KEY"
GLUETUN_KEY_ENV = "GLUETUN_ROTATE_GLUETUN_KEY"

DEFAULT_API_URL = "http://127.0.0.1:9191"
DEFAULT_GLUETUN_URL = "http://127.0.0.1:8000"

PROBE_INTERVAL_SECONDS = 120.0
REFUSALS_BEFORE_ROTATING = 2
REFUSED_STATUSES = frozenset(range(520, 528))
ROTATION_COOLDOWN_SECONDS = 600.0
MAX_ROTATIONS_PER_HOUR = 3
ACCOUNTS_REFRESH_SECONDS = 900.0

VPN_STOP_TIMEOUT_SECONDS = 30.0
NEW_ADDRESS_TIMEOUT_SECONDS = 90.0
GLUETUN_POLL_SECONDS = 3.0

API_TIMEOUT_SECONDS = 10.0
PROBE_TIMEOUT_SECONDS = 15.0
TERMINATE_GRACE_SECONDS = 10.0
HEARTBEAT_INTERVAL_SECONDS = 60.0

MAX_LOG_BYTES = 2 * 1024 * 1024
MAX_RECENT_EVENTS = 50
